apiVersion: v1
kind: Pod
metadata:
  name: TestPod1
  labels:
    name: TestPod1
spec:
  containers:
  - name: TestPod1
    image: tomcat
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
