apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstreplica
spec:
  replicas: 5
  selector:
    app: myfirstreplica
  template:
    metadata:
      name: myfirstreplica
      labels:
        app: myfirstreplica
    spec:
      containers:
        - name: myfirstreplica
          image: tomcat
          ports:
            - containerPort: 9090
